#!/bin/sh
set -eu
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

echo --------------------------------------------
echo Starting Git hook: pre-commit

rush verify-staged

echo Finished Git hook: pre-commit
echo --------------------------------------------
